const { join } = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'),
    ],
    theme: {
        screens: {
            xs: '360px',
            sm: '640px',
            md: '992px',
            lg: '1024px',
            xl: '1200px',
        },
        container: {
            center: true,
        },
        extend: {
            colors: {
                blank: {
                    100: 'rgba(255, 255, 255, 0.1)',
                    200: 'rgba(255, 255, 255, 0.2)',
                    300: 'rgba(255, 255, 255, 0.3)',
                    400: 'rgba(255, 255, 255, 0.4)',
                    500: 'rgba(255, 255, 255, 0.5)',
                    DEFAULT: '#ffffff',
                    600: 'rgba(255, 255, 255, 0.6)',
                    700: 'rgba(255, 255, 255, 0.7)',
                    800: 'rgba(255, 255, 255, 0.8)',
                    900: 'rgba(255, 255, 255, 0.9)',
                },
                grey: {
                    50: '#F9FAFB',
                    100: '#F3F4F6',
                    200: '#E4E7EA',
                    light: '#E4E7EA',
                    300: '#D3D5DA',
                    400: '#9DA4AE',
                    500: '#6C727F',
                    DEFAULT: '#6C727F',
                    600: '#394150',
                    700: '#111826',
                    dark: '#111826',
                },
                primary: {
                    'extra-light': '#F5FCFB',
                    light: '#E6F8F6',
                    medium: '#9DE3DC',
                    DEFAULT: '#09B8A7',
                    shade: '#0BA394',
                    dark: '#098F83',
                },
                secondary: {
                    light: '#D7ECFE',
                    medium: '#8EC1EC',
                    DEFAULT: '#339AF0',
                    dark: '#0B6FC2',
                },
                tertiary: {
                    light: '#DFE6FE',
                    medium: '#9AADE9',
                    DEFAULT: '#1E40AF',
                    dark: '#04248D',
                },
                success: {
                    light: '#E4F1E9',
                    DEFAULT: '#107E1B',
                    dark: '#036407',
                },
                warning: {
                    light: '#FFF4CE',
                    DEFAULT: '#fcca4b',
                    dark: '#C38D00',
                },
                danger: {
                    light: '#FFEDF0',
                    DEFAULT: '#F43F5E',
                    dark: '#802020',
                },
                orange: {
                    light: '#FFEEE1',
                    DEFAULT: '#F97317',
                    dark: '#884f1a',
                },
                accent: {
                    blue: '#226DA8',
                    orange: '#F97317',
                    red: '#F43F5E',
                    green: '#049769',
                    yellow: '#FAB005',
                    purple: '#8B5CF6',
                    brown: '#805D05',
                    'soft-yellow': '#FFEDC0',
                    'soft-green': '#E6F5F0',
                    'soft-red': '#FFF5F7',
                    skillhub: '#1E40AF',
                    karirhub: '#339AF0',
                    sertihub: '#F03E3E',
                    bizhub: '#6741D9',
                    konseling: '#F59E0B',
                },
            },
            backgroundSize: {
                '50%': '50%',
                '45%': '45%',
            },
            fontFamily: {
                sans: ['Inter', 'Helvetica', 'system-ui', 'sans-serif'],
            },
            fontSize: {
                '2xs': ['.625rem', 'auto'],
                xs: ['.75rem', 'auto'],
                sm: ['.875rem', '140%'],
                base: ['1rem', '140%'],
                medium: ['18px', '140%'],
                lg: ['1.25rem', '120%'],
                xl: ['1.5rem', '120%'],
                '2xl': ['2rem', '120%'],
                '3xl': ['2.5rem', '120%'],
            },
            spacing: {
                '9.5': '2.375rem',
                '4.5': '1.125rem',
                '5.5': '1.375rem',
                '13': '3.25rem',
                '15': '60px',
                '18' : '4.5rem',
                '19' : '4.75rem',
                '25' : '6.25rem',
                '30' : '7.5rem',
                '31' : '7.75rem',
                '33' : '8.25rem',
                '35' : '8.75rem',
                '39' : '9.75rem',
                '41' : '10.25rem',
                '45' : '11.25rem',
                '46.25' : '11.5625rem',
                'text-xs': '280px',
                'text-sm': '340px',
                'text-2sm': '400px',
                'text-3sm': '448px',
                'text-md': '481px',
                'text-lg': '584px',
                'text-1lg': '684px',
                'text-2lg': '744px',
                'text-xl': '790px',
                'text-2xl': '920px',
                '-full': '-100%',
                'full': '100%',
            },
            maxWidth: {
                '15': '60px',
                '20': '5rem',
                '55': '13rem',
                '64': '16rem',
                '80': '20rem',
                'text-xs': '280px',
                'text-sm': '340px',
                'text-2sm': '400px',
                'text-3sm': '448px',
                'text-md': '481px',
                'text-lg': '584px',
                'text-1lg': '684px',
                'text-2lg': '744px',
                'text-xl': '790px',
                'text-2xl': '920px',
            },
            minWidth: {
                '15': '60px',
                'lg': '32rem',
                '2/12': '16.667%',
                'text-xs': '280px',
                'text-sm': '340px',
                'text-2sm': '400px',
                'text-3sm': '448px',
                'text-md': '481px',
                'text-lg': '553px',
                'text-1lg': '684px',
                'text-2lg': '744px',
                'text-xl': '790px',
                'text-2xl': '920px',
            },
            zIndex: {
                '-1': '-1',
            }
        },
    },
    important: true,
    plugins: [
        function ({ addComponents }) {
            addComponents({
                '.container': {
                    maxWidth: '100%',
                    '@screen lg': {
                        maxWidth: '1200px',
                    },
                }
            })
        },
    ],
};

